### ISSUE TITLE
Clean template

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#16]
I think that, other than solving issue #6, before completing the creation of the template, we should clean it:

- remove the `app.py` file from `src` folder maybe replacing it with `__init__.py`)
- remove requirements/requirements*.txt
- empty requirements/requirements.in file
- reduce requirements/requirements_dev.in file to include only dependencies required by implemented automations

**Comment by deusebio** [comment]
But if we say that certain libraries are "core" (such as flake8, pip-tools, mypy, etc), these should go directly in the requirements. Otherwise it would be hard implement basic CI functionalities.

**Comment by NicolaDonelli** [comment]
Of course, I'll clarify the first post

**Comment by deusebio** [comment]
Maybe for the sake of the template, it makes sense to have a simple function that uses standard library functionalities (sum of integers or sum of strings) that we use to implement a simple test

**Comment by NicolaDonelli** [comment]
Actually, there already is a sample test, is there any advantage in changing it?

**Comment by deusebio** [comment]
I thought a simple tests to test whatever there is left in src. Actually now that I'm thinking we could run something with the version (get_version), such that also other instruction in the versioneer file gets executed. Just to have a coverage which is not 0%
