### ISSUE TITLE
Safer PyPI release process using make

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#46]
Since we realized that automatical release on PyPI using CD workflow could be a bit risky, I was wondering if it wouldn't be better to implement a safer release automation using `make` command.
My idea was to implement a command that compiles wheel and distribution, checks whether the compiled distribution is temporary or not and, if it is not temporary, releases it based using `twine` package as described [here](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

What do you think about this?
@CGnal/datascientists @CGnal/developers @CGnal/core @CGnal/visualteam

**Comment by ascartabelli** [comment]
@NicolaDonelli e @deusebio sorry but I'm not getting the issue here: what risks are you talking about?

**Comment by NicolaDonelli** [comment]
The risk is linked to the fact I was explaining in my seminar: the Python Package Index is (correctly) not overwritable so, once you published a package all you can do removing it from public availability but you cannot change or overwrite it.
Since the CD process is automatically activated by some conditions (i.e. a tag with a message starting with "v") this situation could lead to unwanted releases.

@deusebio I agree that the release should be done by a service account and this would hold also for releases done with `make` command since one would be prompted to insert username and API token and the only users allowed to do that are the owners and maintainers of the PyPI project. In my opinion, releases with `make` command under this setting would be safer than automatic releases exactly because one will be required to insert credentials and thus this cannot happen by chance and it cannot be done by unauthorized users (i.e. users that do not have credentials).

**Comment by ascartabelli** [comment]
Ok, now I got the bit that I was missing: thanks @NicolaDonelli.
My suggestion would be: make it automatic if you can rely on a safer trigger (a tag starting with "v" is a bit weak).
Otherwise a manual process is just fine.

**Comment by NicolaDonelli** [comment]
Do you have any suggestion about what trigger could be safer? The only solution I could come up with was the manual trigger, but that would amount to a more risky version of what we achieve with the `make` command...

**Comment by NicolaDonelli** [comment]
I agree that also push permissions could be restricted but that should be done on repo level. I do not think there is a way to do that in the template in a way that could fit most of applications.
