### ISSUE TITLE
Make commands uninstall local package

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#48]
We just noticed that some make commands (all those commands depending on setup_ci and install_tag) remove the local package (i.e. the one currently under development in the repo, installed with `make install`) from the environment.
This is quite annoying, especially in contexts where one is developing a namespace package instead of a simple package (like we do with cgnal namespace) but I don't think it should happen in general.

The quickest solution should be to invert the priority of dependence from `make XXX: $(install_tag) setup_ci` to `make XXX:  setup_ci $(install_tag)`, but I am not completely sure about all the implications of this change.

**Comment by deusebio** [comment]
yes, we can just swap the order, I guess
