### ISSUE TITLE
Make install do not re-install correctly the package

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#49]
We just realized that `make install` does not correctly re-install the package.
In particular, if one runs `make mypy` removes the current package from the environment (since it syncs requirements_ci.txt after running the install_tag, as explained in issue #48 ) but running `make install` afterwards does nothing since it checks for the existence of the `make_cache/.install_tag` file and it actually exists.

@deusebio, I think that `make install` should not be cached at all, only `make dist` should.

**Comment by deusebio** [comment]
Yes, you are right. It is kinda annoying since pip-sync actually uninstalls the package itself. We can easily fix this by removing the "install_tag" too when we sync using pip-sync
