### ISSUE TITLE
make install depends on setup

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#50]
Thanks to @afalcioni I just realized that the `make install` command depends on the `setup` command. This implies that requirements.txt is installed before installing the package but this should not be needed since installing a package with pip should already install all its dependencies.

On the other hand, this behaviour could conflict with those commands that pre-require setup_ci since this implies that running install after setup_ci overwrites requirements_ci with requirements, removing some necessary package (e.g. pytest, mypy, flake8,...).

**Comment by deusebio** [comment]
yes, good catch. 

My proposal would be to make it such that make install does not install dependencies (flag --no-deps on pip). Within make we have other dedicated instructions that take care of dependencies installation, and as you pointed out, this can generate conflicts and inconsistent behaviour. This was install dependency can be seamlessly used both with setup_ci and setup dependecies
