### ISSUE TITLE
parentdir_prefix

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#6]
I just realized that in the setup.cfg file there is this line:
```
parentdir_prefix = python-ci-template
```

To me, it seems quite annoying for a template to have the folder name hardcoded in the configuration file... isn't there a way to make this definition relative to the path where this file is placed (according to the template structure)?

**Comment by deusebio** [comment]
I'm not against. However, I can see that this file should be always checked and modified when starting a new project. I mean, all the keys under "metadata" should be set properly...

If there is an EASY way to do it I'd be fine with, but it may be not straightforward (I cannot think of easy ways to do this, given it is a configuration file. 

In short what I mean is: "I would definitely NOT DO complicated things to get the name of the folder automatically"

**Comment by NicolaDonelli** [comment]
Ok fine. 
Than at least we should replace configuration values that should be changed with placeholders easy to spot

**Comment by ascartabelli** [comment]
What about something along these lines instead?

https://github.com/marketplace/actions/init-action

**Comment by NicolaDonelli** [comment]
> What about something along these lines instead?
> 
> https://github.com/marketplace/actions/init-action

Maybe a little late but I like this! 
It would make it redundant to create a make command to initialize the repo and would automate the process configuration of the repo (did you know, I am a fan of automations?)

**Comment by ascartabelli** [comment]
I like it too, but I think it needs more thought (e.g. dealing with private repos, how to start the process, etc.). 
For the moment being I thought it would be better to start simple and write a bash script as I did.
